mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^PersonHomepage/$', views.PersonHomepage, name='PersonHomepage'),
    url(r'^PersonHomepage/PersonSignup/$', views.PersonSignup, name='PersonSignup'),
    url(r'^PersonHomepage/PersonLogin/$', views.PersonLogin, name='PersonLogin'),
    url(r'^PersonHomepage/Personal_Informations/$', views.Personal_Informations, name='Personal_Informations'),
    url(r'^PersonHomepage/Cv/$', views.Cv, name='Cv'),
    url(r'^PersonHomepage/HomeP/$', views.HomeP, name='HomeP'),
    url(r'^PersonHomepage/Logout/$', views.Logout, name='Logout'),
    url(r'^PersonHomepage/RequestForEntreprise/$', views.RequestForEntreprise, name='RequestForEntreprise'),
    url(r'^PersonHomepage/requests/$', views.RequestsDispachter, name='RequestsDispachter'),
    url(r'^EntrepriseHomepage/$', views.EntrepriseHomepage, name='EntrepriseHomepage'),
    url(r'^EntrepriseHomepage/EntrepriseSignup/$', views.EntrepriseSignup, name='EntrepriseSignup'),
    url(r'^EntrepriseHomepage/HomeE/$', views.HomeE, name='HomeE'),
    url(r'^EntrepriseHomepage/EntrepriseLogin/$', views.EntrepriseLogin, name='EntrepriseLogin'),
    url(r'^EntrepriseHomepage/PersonRequest/$', views.PersonRequest, name='PersonRequest'),
]

polls/models.py
from __future__ import unicode_literals

from django.db import models

class Entreprise(models.Model):
    entrepriseName = models.CharField(max_length=100, primary_key=True)
    entreprisePassword = models.CharField(max_length=200)

class Person(models.Model):
    SIN_Number = models.CharField(max_length=9, primary_key=True)
    Person_Name = models.CharField(max_length=100)
    Person_Password = models.CharField(max_length=500)
    isInEntrepriseName = models.ForeignKey(Entreprise, null=False, default="None",on_delete=models.SET_DEFAULT)

class Requests(models.Model):
    personSINRequests = models.ForeignKey(Person, null=False ,on_delete=models.CASCADE)
    entrepriseNameRequests = models.ForeignKey(Entreprise, null=False ,on_delete=models.CASCADE)
    jobName = models.CharField(max_length=200, null=False)

class Record(models.Model):
    recordFlag = models.BooleanField(default=False, editable=True)
    sinNumberPersonne = models.ForeignKey(Person, on_delete=models.CASCADE)

class PersonalInformations(models.Model):
    adress = models.CharField(max_length=80)
    postalCode = models.CharField(max_length=7)
    sexe = models.CharField(max_length=1)
    personEmail = models.CharField(max_length=50)
    phone = models.CharField(max_length=14)
    sinNumberPersonne = models.ForeignKey(Person , on_delete=models.CASCADE)

polls/forms.py
import logging
from django.db import models
from django.core.validators import RegexValidator
from django import forms

from .models import Person, PersonalInformations, Entreprise

class EntrepriseForm(forms.ModelForm):
    entrepriseName = forms.CharField(label="Entreprise Name")
    entreprisePassword = forms.CharField(widget=forms.PasswordInput, label="Password")
    confirmPassword = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")
    class Meta:
        model = Entreprise
        fields = ('entrepriseName' ,'entreprisePassword',)

    def clean(self):
        cleaned_data = super(EntrepriseForm, self).clean()
        entreprisePassword = cleaned_data.get("entreprisePassword")
        confirmPassword = cleaned_data.get("confirmPassword")

        if entreprisePassword != confirmPassword:
            raise forms.ValidationError(
                "Both passwords do not match"
            )

alphanumeric = RegexValidator(r'^[0-9]*$', 'Only numeric characters are allowed for the Sin number.')
class PersonForm(forms.ModelForm):
    Person_Password = forms.CharField(widget=forms.PasswordInput)
    Confirm_Password = forms.CharField(widget=forms.PasswordInput)
    SIN_Number = forms.CharField(min_length=9, max_length=9, validators=[alphanumeric],label="Sin number")
    class Meta:
        model = Person
        fields = ('SIN_Number', 'Person_Name', 'Person_Password', )

    def clean(self):
        cleaned_data = super(PersonForm, self).clean()
        Person_Password = cleaned_data.get("Person_Password")
        Confirm_Password = cleaned_data.get("Confirm_Password")

        if Person_Password != Confirm_Password:
            raise forms.ValidationError("Both passwords do not match")


SEXE_CHOICES = (
('m','Men'),('w','Women'))
phone = RegexValidator(r'^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$', 'Phone number is not valid.')
postalCode = RegexValidator(r'^[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ] ?[0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]$', 'Postal code is not valid')

class PersonalInformationsForm(forms.ModelForm):
    adress = forms.CharField(max_length=80)
    postalCode = forms.CharField(max_length=7, min_length=6, label="Postal code", validators=[postalCode])
    sexe = forms.CharField(widget=forms.Select(choices=SEXE_CHOICES))
    personEmail = forms.EmailField(label="Email")
    phone = forms.CharField(max_length=14, validators=[phone])
    sinNumberPersonne = forms.ModelChoiceField(queryset=Person.objects.all(),required=False, widget=forms.HiddenInput(), label="")

    class Meta:
        model = PersonalInformations
        fields = ('adress', 'postalCode', 'sexe', 'personEmail','phone', 'sinNumberPersonne')

polls/views.py
import logging
import os
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from django.contrib.auth.hashers import make_password,check_password
from django.http import HttpResponse
from django.utils.encoding import smart_str


from .forms import PersonForm, PersonalInformationsForm, EntrepriseForm
from .models import Entreprise, Person, Record, PersonalInformations, Requests


def index(request):
    Logout(request)
    return render(request, 'index.html')

def EntrepriseHomepage(request):
    return render(request, 'polls/EntrepriseHomepage.html')

def PersonHomepage(request):
    return render(request, 'polls/PersonHomepage.html')

def HomeP(request):
    if  not sessionValidePersonne(request):
        return redirect('PersonSignup')
    name = Person.objects.get(SIN_Number=request.session['SIN_Number']).isInEntrepriseName_id
    return render(request, 'polls/HomeP.html', {'entrepriseName': name})

def RequestForEntreprise(request):
    if  not sessionValidePersonne(request):
        return redirect('PersonSignup')
    entreprises = Entreprise.objects.all()
    return render(request, 'polls/EntrepriseRequest.html', {'entreprises': entreprises})

def PersonRequest(request):
    if  not sessionValideEntreprise(request):
        return redirect('EntrepriseSignup')
    errorMessage = ""
    if request.method == 'POST':
        cvExiste = ""
        cvExistantDoc = Path('Cvs/'+request.POST['SIN_Number']+".docx")
        cvExistantPdf = Path('Cvs/'+request.POST['SIN_Number']+".pdf")
        if cvExistantPdf.exists():
            cvExiste = cvExistantPdf
        elif cvExistantDoc.exists():
            cvExiste = cvExistantDoc
        if os.path.exists(cvExiste):
            with open(cvExiste, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(cvExiste)
                return response
        else:
            errorMessage = "Cv no existant!"
    if request.method == 'GET' and 'Sin' in request.GET:
        person = Person.objects.get(SIN_Number=request.GET['Sin'])
        person.isInEntrepriseName = Entreprise.objects.get(entrepriseName=request.session['entrepriseName'])
        person.save()
        requests = Requests.objects.get(id=request.GET['id'])
        requests.delete()
        return redirect('PersonRequest')
    requests = Requests.objects.filter(entrepriseNameRequests=request.session['entrepriseName'])
    return render(request, 'polls/PersonRequest.html', {'requests': requests, 'errorMessage':errorMessage})

def RequestsDispachter(request):
    if  not sessionValidePersonne(request):
        return redirect('PersonSignup')
    entrepriseName = ""
    if request.method == 'GET':
        entrepriseName = request.GET['entrepriseName']
    if request.method == 'POST':
        requests = Requests()
        requests.personSINRequests = Person.objects.get(SIN_Number=request.session["SIN_Number"])
        requests.entrepriseNameRequests = Entreprise.objects.get(entrepriseName=request.GET['entrepriseName'])
        requests.jobName = request.POST["jobName"]
        requests.save()
        return redirect('HomeP')
    return render(request, 'polls/RequestDispatcher.html', {'entrepriseName': entrepriseName})


def HomeE(request):
    if  not sessionValideEntreprise(request):
        return redirect('EntrepriseSignup')
    entreprise = Entreprise.objects.get(entrepriseName=request.session['entrepriseName'])
    return render(request, 'polls/HomeE.html')

def PersonSignup(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            formFinal = form.save(commit=False)
            formFinal.Person_Password = make_password(formFinal.Person_Password)
            request.session['SIN_Number'] = formFinal.SIN_Number
            formFinal.save()
            return redirect('Personal_Informations')
    else:
        form = PersonForm()
    return render(request, 'polls/PersonSignup.html', {'form': form})

def EntrepriseSignup(request):
    if request.method == 'POST':
        form = EntrepriseForm(request.POST)
        if form.is_valid():
            formFinal = form.save(commit=False)
            formFinal.entreprisePassword = make_password(formFinal.entreprisePassword)
            request.session['entrepriseName'] = formFinal.entrepriseName
            formFinal.save()
            return redirect('HomeE')
    else:
        form = EntrepriseForm()
    return render(request, 'polls/PersonSignup.html', {'form': form})

def Personal_Informations(request):
    if not sessionValidePersonne(request):
        return redirect('PersonSignup')
    if request.method == 'POST':
        try:
            informationsPerson = PersonalInformations.objects.get(sinNumberPersonne=request.session['SIN_Number'])
            informationsPerson.adress = request.POST['adress']
            informationsPerson.postalCode = request.POST['postalCode']
            informationsPerson.sexe = request.POST['sexe']
            informationsPerson.personEmail = request.POST['personEmail']
            informationsPerson.phone = request.POST['phone']
            informationsPerson.save()
            return redirect('HomeP')
        except PersonalInformations.DoesNotExist:
            data = {
                'adress': request.POST['adress'],
                'postalCode': request.POST['postalCode'],
                'sexe': request.POST['sexe'],
                'personEmail': request.POST['personEmail'],
                'phone': request.POST['phone'],
                'sinNumberPersonne': request.session['SIN_Number'],
            }

            form = PersonalInformationsForm(data)
            if form.is_valid():
                form.save()
                return redirect('Cv')
    else:
        form = PersonalInformationsForm()
        try:
            personLogger = PersonalInformations.objects.get(sinNumberPersonne=request.session['SIN_Number'])
            form.fields['adress'].initial = personLogger.adress
            form.fields['postalCode'].initial = personLogger.postalCode
            form.fields['personEmail'].initial = personLogger.personEmail
            form.fields['phone'].initial = personLogger.phone
        except PersonalInformations.DoesNotExist:
            personLogger = None
    return render(request, 'polls/Personal_Informations.html', {'form': form})

def Cv(request):
    if not sessionValidePersonne(request):
        return redirect('PersonSignup')
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        deleteCvExistant(fs, request)
        if myfile.name.endswith('.docx'):
            filename = fs.save('Cvs/'+request.session['SIN_Number']+".docx", myfile)
        elif myfile.name.endswith('.pdf'):
            filename = fs.save('Cvs/'+request.session['SIN_Number']+".pdf", myfile)
        else:
            errorMessage = 'The document is not compatible'
            return render(request, 'polls/Cv.html', {'errorMessage': errorMessage})
        return render(request, 'polls/HomeP.html')
    return render(request, 'polls/Cv.html')

def PersonLogin(request):
    if request.method == 'POST':
        try:
            personLogin = Person.objects.get(SIN_Number=request.POST['SIN_Number'])
        except Person.DoesNotExist:
            return redirect('PersonLogin')
        if check_password(request.POST['Person_Password'], personLogin.Person_Password):
            request.session['SIN_Number'] = personLogin.SIN_Number
            return redirect('HomeP')
    return render(request, 'polls/PersonLogin.html')

def EntrepriseLogin(request):
    if request.method == 'POST':
        try:
            entreprise = Entreprise.objects.get(entrepriseName=request.POST['entrepriseName'])
        except Entreprise.DoesNotExist:
            return redirect('EntrepriseLogin')
        if check_password(request.POST['entreprisePassword'], entreprise.entreprisePassword):
            request.session['entrepriseName'] = entreprise.entrepriseName
            return redirect('HomeE')
    return render(request, 'polls/EntrepriseLogin.html')

def sessionValidePersonne(request):
    if 'SIN_Number' not in request.session:
        return False
    return True

def sessionValideEntreprise(request):
    if 'entrepriseName' not in request.session:
        return False
    return True

def deleteCvExistant(fs, request):
    cvExistantDoc = Path('Cvs/'+request.session['SIN_Number']+".docx")
    cvExistantPdf = Path('Cvs/'+request.session['SIN_Number']+".pdf")
    if cvExistantPdf.exists():
        fs.delete(cvExistantPdf)
    elif cvExistantDoc.exists():
        fs.delete(cvExistantDoc)

def Logout(request):
    if 'entrepriseName' in request.session:
        del request.session['entrepriseName']
        return redirect('EntrepriseLogin')
    elif 'SIN_Number' in request.session:
        del request.session['SIN_Number']
        return redirect('PersonLogin')

polls/templates/polls/Cv.html
{% extends 'base.html' %} {% block content %}
<nav>
  <h1> Cv </h1>
  <h3> Only word and pdf files </h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input required type="file" name="myfile">
    <p></p>
    <button type="submit">Upload Cv</button>
  </form>
  {% if errorMessage %}
  <p>File was not upload : {{ errorMessage }}</p>
  {% endif %}
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/EntrepriseHomepage.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <div id="center"><a href={% url 'EntrepriseLogin' %}>Login</a></div>
</nav>
<aside>
  <div id="center"><a href={% url 'EntrepriseSignup' %}>Sign up</a></div>
</aside>

{% endblock %}

polls/templates/polls/EntrepriseLogin.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <form method="post">
    {% csrf_token %}
    <table>
      <tr>
        <th><label for="id_entrepriseName">Entreprise Name:</label></th>
        <td><input type="text" name="entrepriseName" required id="id_entrepriseName" /></td>
      </tr>
      <tr>
        <th><label for="id_entreprisePassword">Password:</label></th>
        <td><input type="password" name="entreprisePassword" required id="id_entreprisePassword" /></td>
      </tr>
    </table>
    <input type="submit" value="Login">
  </form>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/EntrepriseRequest.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <h1>Select the Company :</h1>
  <ul>
    {% for entreprise in entreprises %}
    <li>
      <a href=/polls/PersonHomepage/requests?entrepriseName={{entreprise.entrepriseName}}>{{ entreprise.entrepriseName }}</a>
    </li>
    {% endfor %}
  </ul>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/EntrepriseSignup.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Sign up">
  </form>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/HomeE.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <div id="center"><a href={% url 'PersonRequest' %}>Requests</a></div>
</nav>
<aside>
  <div id="center"><a href={% url 'Logout' %}>Logout</a></div>
</aside>

{% endblock %}

polls/templates/polls/HomeP.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <p>Company name : {{ entrepriseName }} </p>
  <a href={% url 'Cv' %}><button>Reupload Cv</button></a>
  <p></p>
  <a href={% url 'Personal_Informations' %}><button>Change personal informations</button></a>
  <p></p>
  <a href={% url 'RequestForEntreprise' %}><button>Make a request to an entreprise</button></a>
</nav>
<aside>
  <div id="center"><a href={% url 'Logout' %}>Logout</a></div>
</aside>

{% endblock %}

polls/templates/polls/PersonHomepage.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <div id="center"><a href={% url 'PersonLogin' %}>Login</a></div>
</nav>
<aside>
  <div id="center"><a href={% url 'PersonSignup' %}>Sign up</a></div>
</aside>

{% endblock %}

polls/templates/polls/PersonLogin.html
{% extends 'base.html' %} {% block content %}
<nav>
  <form method="post">
    {% csrf_token %}
    <table>
      <tr>
        <th><label for="id_SIN_Number">Sin number:</label></th>
        <td><input type="text" name="SIN_Number" maxlength="9" minlength="9" required id="id_SIN_Number" /></td>
      </tr>
      <tr>
        <th><label for="id_Person_Password">Password:</label></th>
        <td><input type="password" name="Person_Password" required id="id_Person_Password" /></td>
      </tr>
    </table>
    <input type="submit" value="Login">
  </form>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/PersonRequest.html
{% extends 'base.html' %} {% block content %}
<nav>
  <h1>Requests</h1>
  <ul>
    {% for request in requests %}
    <li>
      <h3>Person SIN Number : {{ request.personSINRequests.SIN_Number }}</h3> Job application : {{request.jobName}}
      <p></p>
      <form method="post">
        {% csrf_token %}
        <input value={{request.personSINRequests.SIN_Number}} name="SIN_Number" type="hidden" />
        <span style="color:red">{{errorMessage}}</span>
        <input type="submit" value="Get cv">
      </form>
      <p></p>
      <a href=/polls/EntrepriseHomepage/PersonRequest/?Sin={{request.personSINRequests.SIN_Number}}&id={{request.id}}>Hire</a>
    </li>
    {% endfor %}
  </ul>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/PersonSignup.html
{% extends 'base.html' %} {% block content %}
<nav>
  <form method="post">
    {% csrf_token %} {% for field in form %} {{ field.errors }} {{field.label | linebreaks}} {{ field }} {% endfor %}
    <p></p>
    <input type="submit" value="Sign up">
  </form>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/Personal_Informations.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <form method="post">
    {% csrf_token %} {% for field in form %} {{ field.errors }} {{field.label | linebreaks}} {{ field }} {% endfor %}
    <p></p>
    <input type="submit" value="Done">
  </form>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/RequestDispatcher.html
{% extends 'base.html' %} {% block content %}
<nav>
  Chosen Company : <b> {{ entrepriseName }} </b>
  <form method="post">
    {% csrf_token %}
    <table>
      <tr>
        <th><label for="id_JobName">Job name:</label></th>
        <td><input type="text" name="jobName" required /></td>
      </tr>
    </table>
    <input type="submit" value="Submit">
  </form>
</nav>
<aside>
</aside>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
<nav>
  <div id="center"><a href={% url 'EntrepriseHomepage' %}>Company</a></div>
</nav>
<aside>
  <div id="center"><a href={% url 'PersonHomepage' %}>Person</a></div>
</aside>

{% endblock %}